[workspace]
members = [
    "zomes/**/coordinator",
    "zomes/**/integrity",
]

resolver = "2"

[workspace.dependencies]
hdi = "0.4.1-rc.1"
hdk = "0.3.1-rc.1"
serde = "1"

[workspace.lints.rust]
unsafe_code = "forbid"
