name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: holochain-performance-testing
          extraPullNames: holochain-ci
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Get NPM cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: nix develop .#ci --command npm ci

      - name: Format (TypeScript)
        run: nix develop .#ci --command npm run format:check

      - name: Lint (TypeScript)
        run: nix develop .#ci --command npm run lint:check

      - uses: actions/cache@v4
        with:
          path: |
            .cargo/bin/
            .cargo/registry/index/
            .cargo/registry/cache/
            .cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Format (Rust)
        run: nix develop .#ci --command cargo fmt -- --check

      - name: Lint (Rust)
        run: nix develop .#ci --command cargo clippy --no-deps --all-targets -- -D warnings

      - name: Build hApps
        run: nix develop .#ci --command ./scripts/build_happs.sh
